# Form implementation generated from reading ui file 'd:\original\coding\invoices-reader\db.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 280)
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 341, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 4)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.load_in_main_ui = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.load_in_main_ui.setObjectName("load_in_main_ui")
        self.gridLayout.addWidget(self.load_in_main_ui, 1, 1, 1, 1)
        self.export_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 1, 2, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "مسلسل"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "التاريخ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "عدد الفواتير"))
        self.pushButton_4.setText(_translate("Dialog", "خروج"))
        self.load_in_main_ui.setText(_translate("Dialog", "عرض في البرنامج"))
        self.export_btn.setText(_translate("Dialog", "تصدير"))
        self.delete_btn.setText(_translate("Dialog", "حذف"))
